spring:
  profiles:
    #environment
    active: test
  application:
    name: chatroom
  datasource:
    url: jdbc:mysql://${chatroom.mysql.ip}:${chatroom.mysql.port}/${chatroom.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${chatroom.mysql.username}
    password: ${chatroom.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis server addr
    host: ${chatroom.redis.host}
    # Redis server port
    port: ${chatroom.redis.port}
    # database index, default 0
    database: 0
    # timeout threshold
    timeout: 1800000
    # password
    password: ${chatroom.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

wx:
  mp:
    callback: ${chatroom.wx.callback}
    configs:
      - appId: ${chatroom.wx.appId} # 第一个公众号的appid
        secret: ${chatroom.wx.secret} # 公众号的appsecret
        token: ${chatroom.wx.token} # 接口配置里的Token值
        aesKey: ${chatroom.wx.aesKey} # 接口配置里的EncodingAESKey值

jwt:
  secret: ${chatroom.jwt.secret}